/**
 * Generated by scripts/optimize-images.mjs. Do not edit.
 *
 * Real dimensions of every photograph and the widths that exist for each, so
 * a component can emit correct width/height and a srcset that never points at
 * a file that was not produced.
 */

export interface PhotoAsset {
  readonly id: string;
  readonly width: number;
  readonly height: number;
  readonly widths: readonly number[];
}

export const PHOTOS = {
  "arbeit-stehfalz": {
    "id": "arbeit-stehfalz",
    "width": 800,
    "height": 617,
    "widths": [
      480,
      800
    ]
  },
  "dach-first-ziegel": {
    "id": "dach-first-ziegel",
    "width": 800,
    "height": 605,
    "widths": [
      480,
      800
    ]
  },
  "dach-offen-geruest": {
    "id": "dach-offen-geruest",
    "width": 800,
    "height": 617,
    "widths": [
      480,
      800
    ]
  },
  "dachgeschoss-ausgebaut": {
    "id": "dachgeschoss-ausgebaut",
    "width": 760,
    "height": 1013,
    "widths": [
      480
    ]
  },
  "dachrinne-detail": {
    "id": "dachrinne-detail",
    "width": 474,
    "height": 347,
    "widths": [
      474
    ]
  },
  "dachstuhl-offen": {
    "id": "dachstuhl-offen",
    "width": 800,
    "height": 617,
    "widths": [
      480,
      800
    ]
  },
  "geruest-luftbild": {
    "id": "geruest-luftbild",
    "width": 800,
    "height": 617,
    "widths": [
      480,
      800
    ]
  },
  "haus-schiefer-fertig": {
    "id": "haus-schiefer-fertig",
    "width": 1184,
    "height": 888,
    "widths": [
      480,
      800
    ]
  },
  "kaminkopf-verkleidet": {
    "id": "kaminkopf-verkleidet",
    "width": 629,
    "height": 629,
    "widths": [
      480
    ]
  },
  "kaminkopf": {
    "id": "kaminkopf",
    "width": 1485,
    "height": 1114,
    "widths": [
      480,
      800,
      1200
    ]
  },
  "moos-nordseite": {
    "id": "moos-nordseite",
    "width": 800,
    "height": 605,
    "widths": [
      480,
      800
    ]
  },
  "moos-vorher-nachher": {
    "id": "moos-vorher-nachher",
    "width": 800,
    "height": 605,
    "widths": [
      480,
      800
    ]
  },
  "natursteinmauer": {
    "id": "natursteinmauer",
    "width": 800,
    "height": 632,
    "widths": [
      480,
      800
    ]
  },
  "pflaster-halb-gereinigt": {
    "id": "pflaster-halb-gereinigt",
    "width": 800,
    "height": 632,
    "widths": [
      480,
      800
    ]
  },
  "schiefer-dachfenster": {
    "id": "schiefer-dachfenster",
    "width": 474,
    "height": 315,
    "widths": [
      474
    ]
  },
  "schiefer-detail": {
    "id": "schiefer-detail",
    "width": 568,
    "height": 545,
    "widths": [
      480
    ]
  },
  "schiefer-verlegen": {
    "id": "schiefer-verlegen",
    "width": 474,
    "height": 338,
    "widths": [
      474
    ]
  },
  "spenglerei-anschluss": {
    "id": "spenglerei-anschluss",
    "width": 800,
    "height": 450,
    "widths": [
      480,
      800
    ]
  },
  "terrasse-reinigung": {
    "id": "terrasse-reinigung",
    "width": 1485,
    "height": 1031,
    "widths": [
      480,
      800,
      1200
    ]
  },
  "ziegel-dunkel-leitern": {
    "id": "ziegel-dunkel-leitern",
    "width": 800,
    "height": 605,
    "widths": [
      480,
      800
    ]
  },
  "ziegel-gebrochen": {
    "id": "ziegel-gebrochen",
    "width": 474,
    "height": 315,
    "widths": [
      474
    ]
  },
  "zink-fallrohr": {
    "id": "zink-fallrohr",
    "width": 474,
    "height": 711,
    "widths": [
      474
    ]
  }
} as const satisfies Record<string, PhotoAsset>;

export type PhotoId = keyof typeof PHOTOS;
