#!/usr/bin/env node
/**
 * Builds responsive derivatives from the photographs in assets/photos.
 *
 * A static host has no image optimiser, so this does the work at build time:
 * every photograph becomes AVIF, WebP and JPEG at the widths the layout
 * actually requests, and a typed manifest records the real dimensions so that
 * `width` and `height` on the img element are never guessed. That is what
 * keeps cumulative layout shift at zero.
 *
 * Source files are never upscaled — a 474px original stays 474px, and the
 * manifest says so, which keeps a small photo out of a slot that would stretch
 * it.
 *
 * Run: npm run images  (part of `npm run build`)
 */
import { readdirSync, mkdirSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, parse } from 'node:path';
import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'assets/photos');
const outDir = join(root, 'public/img');

const WIDTHS = [480, 800, 1200, 1600];

if (!existsSync(source)) {
  console.log('  assets/photos fehlt — nichts zu tun.');
  process.exit(0);
}

mkdirSync(outDir, { recursive: true });

const files = readdirSync(source).filter((f) => /\.(jpe?g|png)$/i.test(f)).sort();
const manifest = [];
let written = 0;
let bytes = 0;

for (const file of files) {
  const { name } = parse(file);
  const input = join(source, file);
  const meta = await sharp(input).metadata();
  const widths = WIDTHS.filter((w) => w <= meta.width).concat(
    WIDTHS.some((w) => w >= meta.width) ? [] : [meta.width],
  );
  if (widths.length === 0) widths.push(meta.width);

  for (const width of widths) {
    const height = Math.round((meta.height / meta.width) * width);
    for (const [format, options] of [
      ['avif', { quality: 52, effort: 4 }],
      ['webp', { quality: 76 }],
      ['jpg', { quality: 80, mozjpeg: true }],
    ]) {
      const target = join(outDir, `${name}-${width}.${format}`);
      // Skip work that is already done: the source photos do not change often
      // and re-encoding 22 files in three formats is slow enough to notice.
      if (existsSync(target) && statSync(target).mtimeMs > statSync(input).mtimeMs) continue;
      const pipeline = sharp(input).resize({ width, height, fit: 'cover' });
      await (format === 'jpg' ? pipeline.jpeg(options) : pipeline[format](options)).toFile(target);
      written += 1;
      bytes += statSync(target).size;
    }
  }

  manifest.push({
    id: name,
    width: meta.width,
    height: meta.height,
    widths,
  });
}

const ts = `/**
 * Generated by scripts/optimize-images.mjs. Do not edit.
 *
 * Real dimensions of every photograph and the widths that exist for each, so
 * a component can emit correct width/height and a srcset that never points at
 * a file that was not produced.
 */

export interface PhotoAsset {
  readonly id: string;
  readonly width: number;
  readonly height: number;
  readonly widths: readonly number[];
}

export const PHOTOS = ${JSON.stringify(
  Object.fromEntries(manifest.map((m) => [m.id, m])),
  null,
  2,
)} as const satisfies Record<string, PhotoAsset>;

export type PhotoId = keyof typeof PHOTOS;
`;

mkdirSync(join(root, 'src/content/photos'), { recursive: true });
writeFileSync(join(root, 'src/content/photos/manifest.ts'), ts, 'utf8');

console.log(
  `  ${files.length} Fotos, ${written} neue Dateien (${(bytes / 1024 / 1024).toFixed(1)} MB), Manifest geschrieben.`,
);
